import { validate } from 'class-validator';
import { CreateUserDto } from './user.dto';

describe('CreateUserDto', () => {
  it('accepts a role ID generated by the RBAC seed', async () => {
    const dto = Object.assign(new CreateUserDto(), {
      email: 'new.member@example.com',
      firstName: 'New',
      lastName: 'Member',
      roleId: '4da101a2-3ea3-31e7-e060-cfd0ec9eaaad',
    });

    expect(await validate(dto)).toEqual([]);
  });
});
