import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Pagination } from '../../../components/shared/Pagination/Pagination'
import { useGetNotificationsQuery, useMarkAllNotificationsReadMutation, useMarkNotificationReadMutation } from '../api/notificationsApi'
import { notificationDestination } from '../utils/notificationDestination'

const filters = ['all', 'unread', 'read'] as const
export function NotificationsPage() {
  const navigate = useNavigate()
  const [readStatus, setReadStatus] = useState<(typeof filters)[number]>('all'); const [page, setPage] = useState(1)
  const { data, isLoading, isFetching, isError, refetch } = useGetNotificationsQuery({ readStatus, page, pageSize: 20 }); const [markRead] = useMarkNotificationReadMutation(); const [markAll, { isLoading: markingAll }] = useMarkAllNotificationsReadMutation()
  const notifications = data?.data.data ?? []; const pagination = data?.data.pagination
  return <section><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold text-slate-900">Notifications</h2><p className="mt-1 text-sm text-slate-600">Updates related to your work and reporting.</p></div><button type="button" disabled={markingAll} className="button-secondary px-3" onClick={() => void markAll()}>Mark all as read</button></div><div className="mb-4 flex gap-1 border-b border-slate-200">{filters.map((filter) => <button key={filter} type="button" onClick={() => { setReadStatus(filter); setPage(1) }} className={`border-b-2 px-3 py-2 text-sm font-medium capitalize ${readStatus === filter ? 'border-blue-600 text-blue-700' : 'border-transparent text-slate-600'}`}>{filter}</button>)}</div>{isLoading && !data && <p className="rounded-md border border-slate-200 bg-white p-4 text-sm text-slate-500">Loading notifications…</p>}{isError && <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-800">Could not load notifications. <button type="button" className="font-medium underline" onClick={() => void refetch()}>Try again</button></div>}{data && notifications.length === 0 && <p className="rounded-md border border-slate-200 bg-white p-6 text-sm text-slate-500">No notifications found.</p>}{notifications.length > 0 && <div className="overflow-hidden rounded-md border border-slate-200 bg-white">{notifications.map((item) => <button key={item.id} type="button" onClick={() => { if (!item.readAt) void markRead(item.id); navigate(notificationDestination(item)) }} className={`block w-full border-b border-slate-100 p-4 text-left last:border-0 hover:bg-slate-50 ${item.readAt ? '' : 'bg-blue-50/40'}`}><div className="flex items-start gap-3"><span className={`mt-2 size-2 rounded-full ${item.readAt ? 'bg-transparent' : 'bg-blue-600'}`} /><span><span className="block text-sm font-medium text-slate-900">{item.title}</span><span className="mt-1 block text-sm text-slate-600">{item.message}</span><span className="mt-2 block text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</span></span></div></button>)}</div>}{pagination && <Pagination page={page} totalPages={pagination.totalPages} hasMore={pagination.hasMore} onPageChange={setPage} disabled={isFetching} />}</section>
}
